#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${ROOT_DIR}/scripts/lib/common.sh"

show_help() {
  cat <<'HELP'
Usage: scripts/import-compose-stacks.sh [--source DIR] [--target DIR] [--force] [--dry-run]

Scans an existing Docker/Compose tree and creates PoDorel compose-stack
templates that can travel in deploy bundles.

Defaults:
  source: parent of this repository
  target: server/templates/compose/imported

The import excludes live .env files, secrets, runtime data, node_modules,
generated output, databases, logs, sockets, archives, and common cache folders.
HELP
  podorel_print_common_help
}

SOURCE_DIR="$(cd "${ROOT_DIR}/.." && pwd)"
TARGET_DIR="${ROOT_DIR}/server/templates/compose/imported"
FORCE=0
DRY_RUN=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --help)
      show_help
      exit 0
      ;;
    --source)
      SOURCE_DIR="$(cd "${2:?Missing value for --source}" && pwd)"
      shift
      ;;
    --target)
      TARGET_DIR="${2:?Missing value for --target}"
      ;;
    --force)
      FORCE=1
      ;;
    --dry-run)
      DRY_RUN=1
      ;;
    *)
      echo "Unknown argument: $1" >&2
      show_help
      exit 2
      ;;
  esac
  shift
done

podorel_setup_logging "import-compose-stacks"
podorel_require_command find
podorel_require_command rsync
podorel_require_command sed
podorel_require_command sort

slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

json_string() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

podorel_step "Compose import plan"
echo "Source: ${SOURCE_DIR}"
echo "Target: ${TARGET_DIR}"

mapfile -t compose_files < <(
  find "$SOURCE_DIR" \
    \( -name .git -o -name node_modules -o -name data -o -name downloads -o -name ollama -o -name models -o -name secrets -o -name .podorel -o -name deploy \) -prune \
    -o -type f \( -name docker-compose.yml -o -name docker-compose.yaml -o -name compose.yml -o -name compose.yaml \) -print | sort
)

if [ "${#compose_files[@]}" -eq 0 ]; then
  echo "No compose files found."
  exit 0
fi

if [ "$DRY_RUN" = "1" ]; then
  printf '%s\n' "${compose_files[@]}"
  exit 0
fi

mkdir -p "$TARGET_DIR"

for compose_file in "${compose_files[@]}"; do
  project_dir="$(dirname "$compose_file")"
  rel_dir="${project_dir#${SOURCE_DIR}/}"
  if [ "$rel_dir" = "$project_dir" ]; then
    rel_dir="$(basename "$project_dir")"
  fi
  id="$(slugify "$rel_dir")"
  if [ "$id" = "" ]; then
    id="$(slugify "$(basename "$project_dir")")"
  fi
  dest="${TARGET_DIR}/${id}"
  if [ -e "$dest" ] && [ "$FORCE" != "1" ]; then
    echo "Skipping existing stack ${id}. Re-run with --force to replace it." >&2
    continue
  fi
  if [ -e "$dest" ]; then
    rm -rf "$dest"
  fi
  mkdir -p "$dest"
  rsync -a \
    --exclude='.git/' \
    --exclude='node_modules/' \
    --exclude='__pycache__/' \
    --exclude='.venv/' \
    --exclude='venv/' \
    --exclude='data/' \
    --exclude='downloads/' \
    --exclude='ollama/' \
    --exclude='models/' \
    --exclude='secrets/' \
    --exclude='dist/' \
    --exclude='build/' \
    --exclude='target/' \
    --exclude='coverage/' \
    --exclude='.cache/' \
    --include='.env.example' \
    --exclude='.env' \
    --exclude='.env.*' \
    --exclude='*.db' \
    --exclude='*.sqlite' \
    --exclude='*.sqlite-*' \
    --exclude='*.sock' \
    --exclude='*.log' \
    --exclude='*.zip' \
    "$project_dir"/ "$dest"/

  compose_name="$(basename "$compose_file")"
  cat > "${dest}/podorel-compose.json" <<JSON
{
  "id": "imported-${id}",
  "version": "1.0.0",
  "name": "$(json_string "$rel_dir")",
  "description": "Imported Docker Compose stack from $(json_string "$rel_dir").",
  "source_path": "$(json_string "$rel_dir")",
  "compose_files": ["$(json_string "$compose_name")"],
  "services": [],
  "environment_files": [".env"],
  "required_files": ["$(json_string "$compose_name")"],
  "notes": ["Generated by scripts/import-compose-stacks.sh. Review compose settings and create .env before deploying."],
  "labels": {"io.podorel.import.source": "compose-scan"}
}
JSON
  if grep -Eq 'env_file:[[:space:]]*(\\[)?\\.env' "$compose_file" && [ ! -f "${dest}/.env.example" ]; then
    printf '# Fill values required by %s\n' "$compose_name" > "${dest}/.env.example"
  fi
  echo "Imported ${rel_dir} -> ${dest}"
done
